language: python
python:
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-docutils automake libtool
install:
  - pip install --upgrade -r requirements.txt
  - ln -sf profiles/default.cfg buildout.cfg
script:
  - buildout -Nv
